language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install flake8 pytest-cov coveralls python-coveralls
  - pip install pytest --upgrade
  - pip install . --no-cache-dir
script: pytest --cov=similaritymeasures -p no:warnings tests/tests.py
before_script:
  - flake8 similaritymeasures
  - pytest --version
after_success:
  - coveralls